server:
  port: 8080
spring:
  application:
    name: randomuser-gateway
  config:
    import: "consul:"
  cloud:
    consul:
      config:
        enabled: true
        fail-fast: true
      discovery:
        enabled: true
      host: localhost
      port: 8500
feign:
  autoconfiguration:
    jackson:
      enabled: true